### ISSUE TITLE
A signer process failed when the signer cannot communicate with redis.

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-signer#59]
I found that a signer failed when the signer cannot communicate with redis.

Its stack trace is:

```
thread 'main' panicked at 'ConnectionManagerError { description: "Could not read enough bytes", cause: Some(Could not read enough bytes) }', src/signer_node/mod.rs:272:25
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: tapyrus_signer::signer_node::SignerNode<T,C>::start
  13: tapyrus_signerd::main
  14: std::rt::lang_start::{{closure}}
  15: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  16: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  18: std::panicking::try
             at src/libstd/panicking.rs:265
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  21: main
  22: __libc_start_main
  23: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by Yamaguchi** [comment]
It seems that it is intended behavior in case redis-server was down.

```
match connection_manager_error_handler {
                Some(ref receiver) => match receiver.try_recv() {
                    Ok(e) => {
                        self.round_timer.stop();
                        panic!(e.to_string());  <========== panic here!
                    }
                    Err(TryRecvError::Empty) => {
                        // No errors.
                    }
                    Err(e) => log::debug!("{:?}", e),
                },
                None => {
                    log::warn!("Failed to get error_handler of connection_manager!");
                }
            }
```
